# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aaa50774780db81c09061b42e85a387271bcae1fc1dcfff6a686e955e69f21c0a686ef98363265006810bb76395fd8bbc79e7153db2126f9008e18be5012664

test:
  secret_key_base: ff1a3408763a076a9131603d631376c5eb52bcf119edc01c10996892f2da35cd260e019dd985006bdc0971d72562fd66dca9eff879a82857dc747d3c8135d2d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
